[package]
name = "blobby"
version = "0.1.0"
authors = ["Samuel Lewis <mazuel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.14"
clap = "3.0.0-beta.1"